import type { Metadata } from "next";
import { Inter, Playfair_Display } from "next/font/google";
import "./globals.css";

import Header from "@/components/Header"
import Footer from "@/components/Footer"
import FreeDelivery from "@/components/FreeDelivery";
import PageTransition from "@/components/PageTransition";

const inter = Inter({ 
  subsets: ["cyrillic", "latin"],
  variable: "--font-inter",
});

const playfair = Playfair_Display({ 
  subsets: ["cyrillic", "latin"],
  variable: "--font-serif",
});

export const metadata: Metadata = {
  title: "Oleknitwear",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ru" className={`${inter.variable} ${playfair.variable}`}>
      <body className="font-sans antialiased bg-stone-50 text-stone-900">
        <FreeDelivery />
        <Header />
        <main>
          <PageTransition>
            {children}
          </PageTransition>
        </main>
        <Footer />
      </body>
    </html>
  );
}